"""
Django settings for mywebsite project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# --------------------------------------------------------------------------
# 环境变量工具：密钥、域名、开关一律从环境变量注入，代码里不硬编码
# 本地开发把变量写在 backend/.env（已被 .gitignore 忽略）；生产用系统环境变量
# --------------------------------------------------------------------------


def _load_dotenv():
    """极简 .env 读取，仅本地开发用，不额外引入依赖。"""
    env_path = Path(__file__).resolve().parent.parent / '.env'
    if not env_path.exists():
        return
    for raw in env_path.read_text(encoding='utf-8').splitlines():
        line = raw.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


_load_dotenv()


def env(name, default=None):
    return os.environ.get(name, default)


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    raw = os.environ.get(name, default) or ''
    return [item.strip() for item in raw.split(',') if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = env_bool('DJANGO_DEBUG', True)

# SECRET_KEY 必须由环境变量提供（本地开发可放 backend/.env）
# 生成：python -c "from django.core.management.utils import get_random_secret_key as k; print(k())"
# 生产环境（DEBUG=False）未配置就直接报错，避免误用公开的兜底密钥
SECRET_KEY = env('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-change-me'
    else:
        raise ImproperlyConfigured(
            'DJANGO_DEBUG=False 时必须通过环境变量 DJANGO_SECRET_KEY 提供密钥'
        )

# 逗号分隔，例如：api.example.com,127.0.0.1,localhost
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost')

# Render 会自动注入外部域名，加进白名单省得手填
if env('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(env('RENDER_EXTERNAL_HOSTNAME'))


# Application definition

INSTALLED_APPS = [
    'simpleui',  # 后台 UI 主题，必须放在 django.contrib.admin 之前
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # —— GitHub 集成新增：跨域 + 第三方登录（allauth 依赖 sites 框架）——
    'corsheaders',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'web',
    'rest_framework',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise 紧随 SecurityMiddleware：生产环境由它托管 /static/ 静态资源
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # CorsMiddleware 必须尽量靠前（在 CommonMiddleware 之前）
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # allauth 账号中间件：处理第三方登录状态
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mywebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mywebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 优先用 DATABASE_URL（托管 Postgres，如 Neon / Supabase / Render PG），
    # 未配置时回落到本地 SQLite —— 本地开发零配置，部署只改环境变量。
    # 注意：PaaS / Serverless 上不能用 SQLite，实例文件系统是临时的。
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# 静态文件：生产环境（DEBUG=False）由 WhiteNoise 直接托管压缩后的静态资源，
# 后台 / SimpleUI 的样式因此不需要额外依赖 Nginx
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# 前端（Vue / Vite）构建产物，参与 Django 的静态文件查找
STATICFILES_DIRS = [BASE_DIR.parent / 'frontend' / 'dist']  # 前端在仓库根下的 frontend/

# python manage.py collectstatic 的输出目录（部署时使用）
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 用户上传的学习资料（开发环境走本地磁盘；配置了对象存储后自动切换）
MEDIA_URL = env('MEDIA_URL', 'media/')
MEDIA_ROOT = BASE_DIR / 'media'

# —— 对象存储（Cloudflare R2 / 任意 S3 兼容服务）——
# 只要设置了 AWS_STORAGE_BUCKET_NAME，上传文件就改走对象存储；
# PaaS / Serverless 的本地磁盘是临时的，必须用它。
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
if AWS_STORAGE_BUCKET_NAME:
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    # R2 形如 https://<account_id>.r2.cloudflarestorage.com
    AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL')
    AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', 'auto')
    # 桶的公开访问域名（R2 控制台开启公开访问后得到，如 pub-xxxx.r2.dev）
    AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN')
    AWS_S3_URL_PROTOCOL = 'https:'
    AWS_S3_FILE_OVERWRITE = False
    # 公开桶：不生成签名临时 URL，file.url 直接是公开地址（论坛图片要能直接显示）
    AWS_QUERYSTRING_AUTH = env_bool('AWS_QUERYSTRING_AUTH', False)
    # R2 不支持对象级 ACL，必须保持 None
    AWS_DEFAULT_ACL = None
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

# 资料上传规则：前后端共用同一套约束
MATERIAL_ALLOWED_EXTENSIONS = [
    '.pdf',
    '.doc',
    '.docx',
    '.ppt',
    '.pptx',
    '.xls',
    '.xlsx',
    '.txt',
    '.md',
    '.zip',
]
MATERIAL_MAX_UPLOAD_SIZE = 50 * 1024 * 1024  # 50 MB

# 论坛附件规则：图片与普通附件分开限制
# 注意：故意**不允许 .svg**——SVG 可以内嵌脚本，是典型的 XSS 载体
ATTACHMENT_IMAGE_EXTENSIONS = ['.png', '.jpg', '.jpeg', '.gif', '.webp']
ATTACHMENT_FILE_EXTENSIONS = [
    '.pdf',
    '.doc',
    '.docx',
    '.ppt',
    '.pptx',
    '.xls',
    '.xlsx',
    '.txt',
    '.md',
    '.zip',
]
ATTACHMENT_MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 图片 5 MB（服务器带宽有限，图片不宜过大）
ATTACHMENT_MAX_FILE_SIZE = 20 * 1024 * 1024  # 其他附件 20 MB


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'web.pagination.StandardPagination',
    'PAGE_SIZE': 12,
    # 限流：全站兜底 + 登录/注册 + 上传三档
    'DEFAULT_THROTTLE_CLASSES': [
        'web.throttles.BurstRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'burst': '600/min',
        'auth': '10/min',
        'upload': '30/hour',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------------------------------
# GitHub 全链路集成：前端站点地址、跨域与 Cookie 策略、第三方登录
# --------------------------------------------------------------------------

# 前端站点地址（GitHub Pages 域名或自定义域名），用于登录后跳回与 CSRF 白名单
FRONTEND_URL = env('FRONTEND_URL', 'http://127.0.0.1:5173').rstrip('/')

# 允许携带 Cookie 跨域调用接口的前端来源（逗号分隔；不能用 *）
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS', FRONTEND_URL)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (
    'accept',
    'authorization',
    'content-type',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

# 跨站写请求（登录 / 评论 / 上传）必须把前端来源加入 CSRF 白名单
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', FRONTEND_URL)

# 前后端不同站部署时 Cookie 必须 SameSite=None + Secure；
# 本地 DEBUG（仅端口不同，同站）保持 Lax，避免 http 下 Cookie 丢失。
if not DEBUG:
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# —— django-allauth + GitHub OAuth ——
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# 自定义适配器：限制第三方登录只能得到普通用户权限，并跳回前端站点
SOCIALACCOUNT_ADAPTER = 'web.adapters.GitHubSocialAccountAdapter'

# 点击按钮直接跳转 GitHub，跳过中间确认页；邮箱由 GitHub 保证，不再二次验证
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'

# allauth 65.x 的新式配置项（避免旧参数弃用告警）
ACCOUNT_LOGIN_METHODS = {'username'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'password1*', 'password2*']

SOCIALACCOUNT_PROVIDERS = {
    'github': {
        # Client ID / Secret 只从环境变量读取，绝不写入仓库
        'APP': {
            'client_id': env('GITHUB_CLIENT_ID', ''),
            'secret': env('GITHUB_CLIENT_SECRET', ''),
            'key': '',
        },
        'SCOPE': ['user:email'],
    }
}
