# Generated by Django 5.2.17 on 2026-09-25 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_forumboard_post_topic_material_review_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='编辑时间'),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='编辑时间'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='精华'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', '提交审核'), ('approved', '审核通过'), ('rejected', '审核驳回'), ('resubmitted', '重新提交')], max_length=16, verbose_name='动作')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='web.material', verbose_name='资料')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审核流水',
                'verbose_name_plural': '审核流水',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('material_submitted', '资料待审'), ('material_approved', '资料通过'), ('material_rejected', '资料驳回'), ('comment_reply', '评论回复'), ('post_reply', '帖子回复')], max_length=24, verbose_name='类型')),
                ('text', models.CharField(max_length=200, verbose_name='内容')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='跳转地址')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='触发人')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '站内通知',
                'verbose_name_plural': '站内通知',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='web_notific_recipie_94bef5_idx')],
            },
        ),
    ]
