# Generated by Django 5.2.17 on 2026-09-25 04:22

import django.db.models.deletion
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='标识')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='简介')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='内容简介')),
                ('file', models.FileField(upload_to=web.models.material_upload_path, verbose_name='文件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('file_ext', models.CharField(blank=True, max_length=10, verbose_name='扩展名')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载量')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='web.category', verbose_name='分类')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                ('tags', models.ManyToManyField(blank=True, related_name='materials', to='web.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '资料',
                'verbose_name_plural': '资料',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下载时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='web.material', verbose_name='资料')),
            ],
            options={
                'verbose_name': '下载记录',
                'verbose_name_plural': '下载记录',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='web.comment', verbose_name='回复对象')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.material', verbose_name='资料')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='web.material', verbose_name='资料')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'material'), name='uniq_favorite_user_material')],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['-created_at'], name='web_materia_created_eeab9d_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['-download_count'], name='web_materia_downloa_3322e7_idx'),
        ),
    ]
