# Generated by Django 5.2.17 on 2026-09-25 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='板块名称')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='标识')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='简介')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '论坛板块',
                'verbose_name_plural': '论坛板块',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='楼层')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '论坛回复',
                'verbose_name_plural': '论坛回复',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '论坛帖子',
                'verbose_name_plural': '论坛帖子',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='material',
            name='review_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='驳回理由'),
        ),
        migrations.AddField(
            model_name='material',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='material',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_materials', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=10, verbose_name='审核状态'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['status', '-created_at'], name='web_materia_status_e1ab54_idx'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='web.post', verbose_name='回复对象'),
        ),
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='topic',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='web.forumboard', verbose_name='板块'),
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='topics', to='web.tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='web.topic', verbose_name='帖子'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-created_at'], name='web_topic_created_863977_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['board', '-created_at'], name='web_topic_board_i_aa54ae_idx'),
        ),
    ]
