# Generated by Django 5.2.17 on 2026-09-25 09:32

import django.db.models.deletion
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_comment_edited_at_post_edited_at_topic_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=web.models.attachment_upload_path, verbose_name='文件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('file_ext', models.CharField(blank=True, max_length=10, verbose_name='扩展名')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('is_image', models.BooleanField(default=False, verbose_name='是图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '论坛附件',
                'verbose_name_plural': '论坛附件',
                'ordering': ('-created_at',),
            },
        ),
    ]
