# Generated by Django 5.2.17 on 2026-09-26 06:16

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='source_url',
            field=models.URLField(blank=True, help_text='文件放在外部（如前端静态站/CDN）时填这里，下载会直接跳转', max_length=500, verbose_name='外链地址'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to=web.models.material_upload_path, verbose_name='文件'),
        ),
    ]
